### ISSUE TITLE
How to adjust the difficulty?

### ISSUE THREAD

**Issue by DHydrogen** [noureddinel/core-bitcoin-net-simulator#2]
Hello dear developers! I have read your paper carefully and run the code locally, but I still don't know how to adjust the difficulty to such as 0.001,0.005...0.1 and so on . I have run several examples, but their difficulty remains 1. I don't know how to get the difficulty according to the inputs. I hope to get your answer, thank you!

**Comment by LinaSalim** [comment]
Hello DHdrogen,

This version of the simulator requires manual configuration of the mining difficulty. However, it is a simple process and can be done by following few steps as listed below: 

1) Understand the difference between mining difficulty and mining target and how to convert between those values (you can check this [link](https://bitcoin.stackexchange.com/questions/30467/what-are-the-equations-to-convert-between-bits-and-difficulty) for a thorough explanation.  

2) Once you calculate the desired mining target,  in the **core-bitcoin-net-simulator**  repository go to **bitcoin/src/chainparams.cpp** source file and change the value of every "genesis.nBits" variable to the desired mining target.  

3) Teardown the previous simulation setup: `python teardown.py`

4) Run your experiment: `python localtestnet.py`

To enhance the practicality of your experiments, you can add a script to the simulator that changes the mining target based on the difficulty value entered by the user; however, keep in mind this approach will also have the overhead of recompiling the source code per experiment. 

Please let us know if you have further inquiries.

**Comment by DHydrogen** [comment]
Thank you for your specific answer !However, for example, I want to adjust the difficulty to 0.1, so I set genesis.nbits to 10 times of the initial value of 0x1d00ffff, that is, 0x12209fff6, but I ran locatestnet.py to report an error :Creating bitcoin-net-simulator_node1_1 ... done
Creating bitcoin-net-simulator_node3_1 ... done
Creating bitcoin-net-simulator_node2_1 ... done
Continers are created successfully.....
Traceback (most recent call last):
  File "localtestnet.py", line 91, in <module>
    C_names_only = containers_names_list[x][27:32]
IndexError: list index out of range
I dont know how to solve it ,looking forward to your reply ^-^

**Comment by DHydrogen** [comment]
Thank you for your specific answer ! However, for example, I want to adjust the difficulty to 0.1, so I set all the "genesis.nbits" to 10 times of the initial value of 0x1d00ffff, that is, 0x12209fff6, (there are two "genesis.nbits",in line 149 and line 267).But I ran locatestnet.py to report an error :
Creating bitcoin-net-simulator_node1_1 ... done
Creating bitcoin-net-simulator_node3_1 ... done
Creating bitcoin-net-simulator_node2_1 ... done
Continers are created successfully.....
Traceback (most recent call last):
File "localtestnet.py", line 91, in 
C_names_only = containers_names_list[x][27:32]
IndexError: list index out of range

the screenshot is in the below
I dont know how to solve it , look forward to your reply ^-^,thank you soooo much!
<img width="292" alt="change_variable" src="https://user-images.githubusercontent.com/39833999/118387041-6994dd00-b64e-11eb-8a33-99d53dde16ae.png">
<img width="295" alt="change_variable_2" src="https://user-images.githubusercontent.com/39833999/118387042-6ac60a00-b64e-11eb-8b5b-b1963de89515.png">
<img width="409" alt="error" src="https://user-images.githubusercontent.com/39833999/118387044-6b5ea080-b64e-11eb-9512-6f59255e7182.png">

**Comment by DHydrogen** [comment]
Thank you very much for your detailed explanation!
I have fully understood the adjustment method of difficulty, however, I still encountered some problems.
In order to adjust the difficulty to 0.1, after calculation, I set the two genesis.nbits in chainparams.cpp to 0x1d00fff6 (this variable only appears in two places in line 149 and line 267). However, after I input and generate two nodes, an error occurred, indicating that there was an error in the container name list. So I printed the specific contents of the list, and was surprised to find that it was empty. Therefore, I am very curious why I only changed the value of nbits to cause this error. I want to know if my operation is correct, if the adjustment difficulty is only changed by this variable, and how can I solve this problem?
This question is very important to my research, so I look forward and really thankful to your reply as soon as possible.
<img width="351" alt="change_variable_1" src="https://user-images.githubusercontent.com/39833999/118524007-4b270280-b770-11eb-946d-045625c4f116.png">
<img width="322" alt="change_variable_2" src="https://user-images.githubusercontent.com/39833999/118524023-4cf0c600-b770-11eb-974c-02f50751388f.png">
<img width="391" alt="error" src="https://user-images.githubusercontent.com/39833999/118524030-4eba8980-b770-11eb-9ef3-42eb3edd1229.png">

**Comment by DHydrogen** [comment]
Dear LinaSalim:
Thank you very much for your detailed explanation!

 I have fully understood the adjustment method of difficulty, however, I still encountered some problems.

 In order to adjust the difficulty to 0.1, after calculation, I set the  two genesis.nbits in chainparams.cpp to 0x1d00fff6 (this variable only  appears in two places in line 149 and line 267). However, after I input  and generate two nodes, an error occurred, indicating that there was an  error in the container name list. So I printed the specific contents of  the list, and was surprised to find that it was empty. Therefore, I am  very curious why I only changed the value of nbits to cause this error. I  want to know if my operation is correct, if the adjustment difficulty  is only changed by this variable, and how can I solve this problem?This question is very important to my research, so I look forward and really thankful to your reply as soon as possible.
 
 
 


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "noureddinel/core-bitcoin-net-simulator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 凌晨2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [noureddinel/core-bitcoin-net-simulator] How to adjust the difficulty? (#2)





 
Hello DHdrogen,
 
This version of the simulator requires manual configuration of the mining difficulty. However, it is a simple process and can be done by following few steps as listed below:
  
 
Understand the difference between mining difficulty and mining target and how to convert between those values (you can check this link for a thorough explanation.
 
 
 
Once you calculate the desired mining target,  in the core-bitcoin-net-simulator  repository go to bitcoin/src/chainparams.cpp source file and change the value of every "genesis.nBits" variable to the desired mining target.
 
 
 
Teardown the previous simulation setup: python teardown.py
 
 
 
Run your experiment: python localtestnet.py
 
  
To enhance the practicality of your experiments, you can add a script to the simulator that changes the mining target based on the difficulty value entered by the user; however, keep in mind this approach will also have the overhead of recompiling the source code per experiment.
 
Please let us know if you have further inquiries.

**Comment by DHydrogen** [comment]
Some additional notes: the default difficulty in the code is 1.0 . In this case, the project can run perfectly. However, as long as "genesis.nBits" are changed, whether the difficulty is raised to greater than 1 or reduced to less than 1, the code will have this error, that is, container_ Name list will be cleared instead of "node1_ 1,node2_ 1......"

**Comment by DHydrogen** [comment]
Problem update:  I used to downloaded the zip code package to the local and renamed the folder, so there was a problem that the name of the docker container did not match. So I used gitclone to pull the code from the remote and run it instead of downloading zip package. However, the above error still occurred: I only changed genesis.bit, but when I regenerated the nodes, C_ names_ only = containers_ names_ List [x] [27:32] error again, so I checked the container_ names_ List. The list is still empty.

**Comment by LinaSalim** [comment]
Problem: This error shows because the node's containers were not generated in the first place.
A fault happened while compiling the modified src, however the docker image was created anyways because the fault was caused by a an internal assert. 

Solution: To solve this problem please comment out the following lines: 152,153,213,270 and rerun your simulation.

**Comment by DHydrogen** [comment]
It works! Thank you so much!!! And so sorry for my frequently disturbance!

**Comment by noureddinel** [comment]
You're welcome, please let us know how the simulator has been useful for
you when you finish your experiments.

Regards.
